using Soenneker.Utils.PooledStringBuilders;

namespace Soenneker.GraphQL.Generator.Generators;

/// <summary>
/// Formatting and description helpers for generated code. Part of <see cref="SchemaGenerator"/>.
/// </summary>
internal sealed partial class SchemaGenerator
{
    private void AppendHeader(ref PooledStringBuilder sb)
    {
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        if (_config.GlobalUsings?.Count > 0)
        {
            foreach (string ns in _config.GlobalUsings.Distinct(StringComparer.Ordinal))
            {
                sb.Append("using ");
                sb.Append(ns);
                sb.AppendLine(";");
            }

            sb.AppendLine();
        }

        if (!string.IsNullOrWhiteSpace(_config.Namespace))
        {
            sb.Append("namespace ");
            sb.Append(_config.Namespace);
            sb.AppendLine(";");
            sb.AppendLine();
        }
    }

    private static void AppendDescription(ref PooledStringBuilder sb, string? description, int indentLevel)
    {
        if (string.IsNullOrWhiteSpace(description))
            return;

        string indent = new(' ', indentLevel * 4);
        sb.Append(indent);
        sb.AppendLine("/// <summary>");

        foreach (string line in description.Split('\n'))
        {
            sb.Append(indent);
            sb.Append("/// ");
            sb.AppendLine(EscapeXml(line.TrimEnd('\r')));
        }

        sb.Append(indent);
        sb.AppendLine("/// </summary>");
    }

    private static string EscapeXml(string value)
        => value
            .Replace("&", "&amp;", StringComparison.Ordinal)
            .Replace("<", "&lt;", StringComparison.Ordinal)
            .Replace(">", "&gt;", StringComparison.Ordinal);

    private static string? GetDescription(GraphQLParser.AST.GraphQLDescription? description)
        => description?.Value.ToString();
}
