using Soenneker.Utils.PooledStringBuilders;

namespace Soenneker.GraphQL.Generator.Generators;

/// <summary>
/// Formatting and description helpers for generated code. Part of <see cref="SchemaGenerator"/>.
/// </summary>
internal sealed partial class SchemaGenerator
{
    private void AppendHeader(ref PooledStringBuilder sb, IEnumerable<string>? fileUsings = null)
    {
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");

        HashSet<string>? mergedUsings = null;

        if (_config.GlobalUsings?.Count > 0)
        {
            mergedUsings = new HashSet<string>(_config.GlobalUsings.Where(static ns => !string.IsNullOrWhiteSpace(ns)), StringComparer.Ordinal);
        }

        if (fileUsings is not null)
        {
            mergedUsings ??= new HashSet<string>(StringComparer.Ordinal);

            foreach (string ns in fileUsings)
            {
                if (!string.IsNullOrWhiteSpace(ns))
                    mergedUsings.Add(ns);
            }
        }

        if (mergedUsings is { Count: > 0 })
        {
            foreach (string ns in mergedUsings.OrderBy(static ns => ns, StringComparer.Ordinal))
            {
                sb.Append("using ");
                sb.Append(ns);
                sb.AppendLine(";");
            }

            sb.AppendLine();
        }

        if (!string.IsNullOrWhiteSpace(_config.Namespace))
        {
            sb.Append("namespace ");
            sb.Append(_config.Namespace);
            sb.AppendLine(";");
            sb.AppendLine();
        }
    }

    private static void AppendDescription(ref PooledStringBuilder sb, string? description, int indentLevel)
    {
        if (string.IsNullOrWhiteSpace(description))
            return;

        string indent = new(' ', indentLevel * 4);
        sb.Append(indent);
        sb.AppendLine("/// <summary>");

        foreach (string line in description.Split('\n'))
        {
            sb.Append(indent);
            sb.Append("/// ");
            sb.AppendLine(EscapeXml(line.TrimEnd('\r')));
        }

        sb.Append(indent);
        sb.AppendLine("/// </summary>");
    }

    private static string EscapeXml(string value)
        => value
            .Replace("&", "&amp;", StringComparison.Ordinal)
            .Replace("<", "&lt;", StringComparison.Ordinal)
            .Replace(">", "&gt;", StringComparison.Ordinal);

    private static HashSet<string> CreateUsingSet(IEnumerable<string>? namespaces = null)
    {
        return namespaces is null
            ? new HashSet<string>(StringComparer.Ordinal)
            : new HashSet<string>(namespaces.Where(static ns => !string.IsNullOrWhiteSpace(ns)), StringComparer.Ordinal);
    }

    private static void AddUsingsForType(ISet<string> usings, string typeName)
    {
        if (string.IsNullOrWhiteSpace(typeName))
            return;

        if (typeName.Contains("List<", StringComparison.Ordinal) ||
            typeName.Contains("Dictionary<", StringComparison.Ordinal) ||
            typeName.Contains("HashSet<", StringComparison.Ordinal) ||
            typeName.Contains("IEnumerable<", StringComparison.Ordinal) ||
            typeName.Contains("IReadOnlyList<", StringComparison.Ordinal) ||
            typeName.Contains("IReadOnlyCollection<", StringComparison.Ordinal))
        {
            usings.Add("System.Collections.Generic");
        }

        if (typeName.Contains("DateOnly", StringComparison.Ordinal) ||
            typeName.Contains("DateTime", StringComparison.Ordinal) ||
            typeName.Contains("DateTimeOffset", StringComparison.Ordinal) ||
            typeName.Contains("Guid", StringComparison.Ordinal) ||
            typeName.Contains("TimeOnly", StringComparison.Ordinal) ||
            typeName.Contains("TimeSpan", StringComparison.Ordinal) ||
            typeName.Contains("Uri", StringComparison.Ordinal) ||
            typeName.Contains("Version", StringComparison.Ordinal))
        {
            usings.Add("System");
        }
    }

    private static string? GetDescription(GraphQLParser.AST.GraphQLDescription? description)
        => description?.Value.ToString();
}
