using System.Text;

namespace Soenneker.GraphQL.Generator.Generators;

/// <summary>
/// Formatting and description helpers for generated code. Part of <see cref="SchemaGenerator"/>.
/// </summary>
internal sealed partial class SchemaGenerator
{
    private void AppendHeader(StringBuilder sb)
    {
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        if (_config.GlobalUsings?.Count > 0)
        {
            foreach (string ns in _config.GlobalUsings.Distinct(StringComparer.Ordinal))
                sb.Append("using ").Append(ns).AppendLine(";");
            sb.AppendLine();
        }
        if (!string.IsNullOrWhiteSpace(_config.Namespace))
        {
            sb.Append("namespace ").Append(_config.Namespace).AppendLine(";");
            sb.AppendLine();
        }
    }

    private static void AppendDescription(StringBuilder sb, string? description, int indentLevel)
    {
        if (string.IsNullOrWhiteSpace(description)) return;
        string indent = new(' ', indentLevel * 4);
        sb.Append(indent).AppendLine("/// <summary>");
        foreach (string line in description.Split('\n'))
            sb.Append(indent).Append("/// ").AppendLine(EscapeXml(line.TrimEnd('\r')));
        sb.Append(indent).AppendLine("/// </summary>");
    }

    private static string EscapeXml(string value)
        => value
            .Replace("&", "&amp;", StringComparison.Ordinal)
            .Replace("<", "&lt;", StringComparison.Ordinal)
            .Replace(">", "&gt;", StringComparison.Ordinal);

    private static string? GetDescription(GraphQLParser.AST.GraphQLDescription? description)
        => description?.Value.ToString();
}
